### ISSUE TITLE
Improve date UX on frontend

### ISSUE THREAD

**Issue by MankiratSingh1315** [MicrosoftStudentChapter/Linky#12]
Add some conditions :-
1. We can't add a date before today
2. Give error if date is invalid like if month is 14 or day is 32
![image](https://github.com/MicrosoftStudentChapter/Link-Generator/assets/120726854/beb99b5c-1b5b-4fe2-8e80-91167155d411)
3. Add a no expiry button
4. A big plus if common expiry options like 1 week, 2 week, month and a year are also added

**Comment by vishnu1345** [comment]
I want to work on this

**Comment by vishnu1345** [comment]
I have fixed all above issues (also added a common expiry option) and created PR for this , please tell me if any change is needed

**Comment by Sims2802** [comment]
Would like to work on this issue
