### ISSUE TITLE
Create a separate route on backend to veiw all the urls generated till now

### ISSUE THREAD

**Issue by MankiratSingh1315** [MicrosoftStudentChapter/Linky#13]

**Comment by adityacodes30** [comment]
i think i saw an api endpoint ? has this already been done @utkarsh-1905 ?

**Comment by MankiratSingh1315** [comment]
Yes there's a route /links/all which gives all the links in `<short-link-name> - <long-link>` format but i think it's too messy to view😅
Returning it in a JSON format will be better or if a template is created to view it properly

**Comment by utkarsh-1905** [comment]
@adityacodes30 that is hack, got no better idea in exams

@MankiratSingh1315 probably make an admin portal or something as part of the package

**Comment by MankiratSingh1315** [comment]
#17 #18 and #19 issues are on it
